config/routes.rb
Rails.application.routes.draw do
  resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :author_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
  
  resources :articles do
    resources :comments
    resources :attachments
  end

  root to: "articles#index"

  resources :tags

  resources :authors

end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  has_many :attachments


  #This validates presence of title, and makes sure that the length is not more than 140 words
  validates :title, presence: true, length: {maximum: 140}
  #This validates presence of body
  validates :body, presence: true

  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  def tag_list
    # tags.join(", ")
    # self.tags.collect do |tag|
    #   tag.name
    # end.join(", ")
  end

  def tag_list=(tags_string)

    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq

    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags

  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login, except: [:index,:show]

  include ArticlesHelper
  # Index action to render all articles
  def index
    @articles = Article.all
  end

  # New action for creating article
  def new
    @article = Article.new
    @attachment = Attachment.new
    @attachment.article_id = @article.id
  end

  # Create action saves the article into database
  def create
    @article = Article.new article_params

    if @article.save
      flash[:notice] = "Article '#{@article.title}' Successfully created!"
      redirect_to article_path(@article)
    else
      flash[:alert] = "Error creating new article!"
      render :new
    end
  end

  # Edit action retrives the article and renders the edit page
  def edit
     @article = Article.find(params[:id])
     @attachment = Attachment.new
     @attachment.article_id = @article.id
   end

  def update
     @article = Article.find(params[:id])
     if @article.update(article_params)
       flash[:notice] = "Article '#{@article.title}' Updated!"
       redirect_to article_path(@article)
       # redirect_to(:action => 'articles#show')
     else
       render 'edit'
     end
  end

  # The show action renders the individual article after retrieving the the id
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  # The destroy action removes the article permanently from the database
  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      flash[:notice] = "Article '#{@article.title}' Successfully deleted!"
      redirect_to articles_path
    else
      flash[:alert] = "Error deleting Article '#{@article.title}'!"
    end
  end

  private

  # def find_article
  #   @article = Article.find(params[:id])
  # end

end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
end

app/views/articles/_attachment.html.erb
<div>
  <p><strong>Image:</strong></p>
  <p><%= image_tag attachment.image.url %></p>
  <br/>

</div>

app/views/articles/_comment.html.erb
<div>
  <p>by <strong><%= comment.author_name %></strong></p>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
  <br>
</div>

app/views/articles/_form.html.erb
<h1>Create New Article</h1>

<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <% if @article.image.exists? %>
        <%= image_tag @article.image.url %><br/>
    <% end %>
    <%= f.label :image, "Attach a New Image" %><br />
    <%= f.file_field :image %>
  </p>  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article), class: 'article_title',
      id: "article_#{article.id}" %>
      <!-- <a href="/articles/1">First Sample Article</a>
 -->
    </li>
  <% end %>
</ul>

<% if logged_in? %>
  <%= link_to "Create a New Article", new_article_path, class: "new_article" %>
<% end %>

<%= link_to "List All Tags", tags_path, class: "new_article" %>

app/views/articles/new.html.erb
<h1>Create New Article</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<% if logged_in? %>
  <p>
    <%= link_to "delete", article_path(@article), data: {confirm: "Really delete the article?"}, method: :delete, class: "new_article" %>
    <%= link_to "edit", edit_article_path(@article), class: "new_article" %>
  </p>
<% end %>
<p class="tag_list">
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<br>

<% if @article.image.exists? %>
    <%= image_tag @article.image.url(:medium) %><br/>
    <!-- <%#= render partial: 'articles/attachment', collection: @article.attachments %> -->
<% end %>

  <p>
    <%= @article.body %>
  </p>
  <h3>Comments(<%= @article.comments.size %>)</h3>
  <%= render partial: 'articles/comment', collection: @article.comments %>
  <br>
  <%= render partial: 'comments/form' %>
  <br>

<%= link_to "<< Back to Articles List", articles_path %>