config/routes.rb
Rails.application.routes.draw do
  resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :author_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
  
  resources :articles do
    resources :comments
    resources :attachments
  end

  root to: "articles#index"

  resources :tags

  resources :authors

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :articles, through: :taggings

  def to_s
    name
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :require_login, only: [:destroy]

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def edit

  end

  def destroy
    @tag = Tag.find(params[:id])

    if @tag.destroy
      flash[:notice] = "Tag '#{@tag.name}' Successfully deleted!!"
      redirect_to tags_path
    else
      flash[:alert] = "ERRO DELETING TAG '#{@tag.name}'!!"
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
  <h1>All Tags(<%= @tags.size %>)</h1>

  <ul id="articles">
    <p>
      <% @tags.each do |tag| %>
        <li>
          <%= link_to tag.name, tag_path(tag) %>
          <% if logged_in? %>
            <%= link_to "Delete", tag_path(tag), data: {:confirm => "This will delete the tag #{tag.name}"}, method: :delete, class: "new_article"  %>
          <% end %>
        </li>
      <% end %>
    </p>
  </ul>
  <br>
  <%= link_to "<< Back to Articles List", articles_path, class: "new_article"  %>
</div>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %>(<%= @tag.articles.size %>)</h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>
<br>
<%= link_to "<< Back to Post List", articles_path %>
<% if logged_in? %>
  <%= link_to 'Edit', edit_tag_path, class: "new_article" %>
<% end %>
<%= link_to 'All Tags', tags_path, class: "new_article" %>